### ISSUE TITLE
Gpsd.stop() doesn't close the connection socket (to be fixed)

### ISSUE THREAD

**Issue by tetherit** [rccursach/gpsd_client#1]
Great gem, thank you for that!!

Looking at the code, it seems the socket is now closed? - Can this line be removed from the Readme? < "Gpsd.stop() doesn't close the connection socket (to be fixed)" :)

**Comment by rccursach** [comment]
Yes it was solved, but i missed that comment from the example. Thanks for letting me know. Feel free to open another issue or pull request if something doesn't work properly.

The comment in question was removed [here](https://github.com/rccursach/gpsd_client/commit/7288c67c62af657448abceb8109d31299f0e9380)
